language: scala
scala:
  - 2.13.0
jdk:
  - openjdk8
  - openjdk11

script:
  # Validate formatting
  - pre-commit run -a
  - sbt clean coverage test coverageAggregate coverageOff
after_success:
  # Upload coverage reports to codecov.io
  - bash <(curl -s https://codecov.io/bash) -t 5e8553fe-5357-46a0-ae90-0b373de9e7ac

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2
    - $HOME/.sbt
