coverage:
  status:
    patch:
      default:
        target: 50%
        threshold: 0%
        branches:
          - master
          - prototype
    project:
      default:
        # TODO: Use better coverage configs after adding better unit test coverage
        target: 50%
        threshold: 0%
        branches:
          - master
          - prototype
